import Head from "next/head";
import { Inter } from "@next/font/google";
import MaterialTable from "material-table";
import { Button } from "@mui/material";
import { useEffect } from "react";
const calcDataType = (current: Date, date: number) => {
  const day = new Date(
    current.getFullYear(),
    current.getMonth(),
    date
  ).getDay();
  console.dir(day);
  if (day === 6) {
    return "holiday";
  } else if (day === 5) {
    return "saturday";
  }
  return;
};
export default function Home() {
  const current = new Date();
  const month = current.getMonth();
  const title: string = `勤怠（${month + 1}月）`;
  const rowStyle: any = { holiday: "pink", saturday: "#e0e9f7" };
  useEffect(() => {}, []);
  //なんか、OPTIONの方でエラーを吐き出しまくっている。後で修正
  const data = [];
  const lastDay = new Date(current.getFullYear(), month, 0).getDate();
  for (let i = 1; i <= lastDay; i++) {
    data.push({
      code: i,
      in: "1234",
      dateType: calcDataType(current, i),
    });
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ backgroundColor: "white" }}>
          <Button variant="contained">出勤</Button>
          <Button variant="contained">退勤</Button>
        </div>
        <div>
          <MaterialTable
            title={title}
            columns={[
              { title: "日付", field: "code", type: "numeric" },
              { title: "出勤", field: "in" },
              { title: "退勤", field: "out" },
              { title: "稼働時間", field: "worktime" },
              { title: "残業時間", field: "overtime" },
            ]}
            data={data}
            options={{
              sorting: true,
              headerStyle: {
                backgroundColor: "#01579b",
                color: "#FFF",
              },
              rowStyle: (rowData) => {
                return {
                  fontFamily: "Mulish-Regular",
                  backgroundColor: rowStyle[rowData.dateType],
                };
              },
              defaultExpanded: () => {
                return true;
              },
            }}
          />
        </div>
      </main>
    </>
  );
}
